### ISSUE TITLE
pathway phenotype profiles

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/analysis-sandbox#2]
It would be great if we had an easy way to lift our phenotype profiles associated with specific genes (also perhaps via orthology) to their respective pathways (such as to a reactome ID). @jpgourdine would like to use this in combination with our metabolite mapping to reactome pathways for variant prioritization. 

No specific implementation recommendations just yet. Looking for ideas and discusssion.
 @drseb @julesjacobsen @cmungall

**Comment by kshefchek** [comment]
I believe these are now being cached in solr via the query: https://github.com/monarch-initiative/monarch-cypher-queries/blob/master/src/main/cypher/golr-loader/pathway-phenotype.yaml
